### ISSUE TITLE
uvloop support for Windows

### ISSUE THREAD

**Issue by pamodm** [jorgenosberg/retrievAI#1]
I tried setting this up in a Win 11 machine. However, it fails during installation of uvloop which throws out an error "uvloop does not support Windows at the moment". Not sure whether to proceed further ignoring this error?

**Comment by jorgenosberg** [comment]
Hi, @pamodm! Thanks for adding an issue and making me aware of this. After looking around and testing on a Windows machine, it appears that `uvloop` is just an extra optional dependency, so I've removed the dependency from the `requirements.txt` file. Just pull the latest version from `main` and run `pip install -r requirements.txt` again – and you're good to go :)

**Comment by pamodm** [comment]
Hi,
Thank you very much for fixing it. It works fine now.
